### ISSUE TITLE
Resize the main image to allow the larger navbar and navbar text

### ISSUE THREAD

**Issue by vibeyInfotech** [vibeyInfotech/Project_02#1]
make the main image small to allow the larger navbar and navbar text

**Comment by suresh8919** [comment]
Hey @vibeyInfotech I'm interested to contribute Please assign me this

**Comment by Prasanthisandaka2005** [comment]
Hello @vibeyInfotech Could you kindly assign this task to me? I'm excited about the opportunity to make your website great!

**Comment by rajput999** [comment]
Hello @vibeyInfotech can you please asign this task to me.
