### ISSUE TITLE
Align the "Lets Talk" and "Portfolio" button

### ISSUE THREAD

**Issue by vibeyInfotech** [vibeyInfotech/Project_02#2]
Add Padding to the "Lets Talk" and "Portfolio" button

**Comment by suresh8919** [comment]
Hello @vibeyInfotech  I'm interested to contribute Please assign to me

**Comment by rajput999** [comment]
hello @vibeyInfotech can you please asign this task to me.

**Comment by seabeePraveen** [comment]
hii @vibeyInfotech  please assign this task to me
