### ISSUE TITLE
Align the "Book landing page design" label

### ISSUE THREAD

**Issue by vibeyInfotech** [vibeyInfotech/Project_02#3]
Align the "Book landing page design" label

**Comment by Prasanthisandaka2005** [comment]
Hello @vibeyInfotech 

Could you provide more details about the task? Please assign it to me. I'm excited to help enhance our website.

**Comment by seabeePraveen** [comment]
@vibeyInfotech i will be really helpful to this issue please assign this to me

**Comment by aasthalovespasta** [comment]
@vibeyInfotech It will be great if you assign me this issue and I will try to complete it on time
